### PR TITLE
Updated datasets to clean up legacy code #1522

### PR DESCRIPTION
**Pull request by abhinavsp0730**
Hey, this is Abhinav Prakash. I've fixed
some of the issues. I'll do the rest of the updates tomorrow.

### CODE REVIEW

**Comment by abhinavsp0730** [comment]
Hey, @Conchylicultor would you please review it.

**Comment by Conchylicultor** [comment]
Awesome work! Thank you!

**Comment by Conchylicultor** [comment]
I ended up submitting https://github.com/tensorflow/datasets/pull/1522 first which was more complete. Could you sync up and resolve merge conflicts ? Or open a new PR with the datasets left ?

**Comment by abhinavsp0730** [comment]
Hey, @Conchylicultor I've resolved the merge conflicts

**Pull request merged**
