### PR TITLE
Spine web dataset

### PR DESCRIPTION
**Pull request by chriszhou0916**
I created a draft version of #974 

Please let me and @leohu6 know what we need to change. 

The dataset loads fine but it is having trouble with one of the tests. See error below. We're not sure what is causing it. We followed the documentation while writing the test script.

Help needed!

```
ERROR: test_download_and_prepare_as_dataset (__main__.SpineWebTest)
test_download_and_prepare_as_dataset (__main__.SpineWebTest)
Run the decorated test method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/testing/test_utils.py", line 214, in decorated
    f(self, *args, **kwargs)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/testing/dataset_builder_testing.py", line 223, in test_download_and_prepare_as_dataset
    self._download_and_prepare_as_dataset(self.builder)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/testing/dataset_builder_testing.py", line 246, in _download_and_prepare_as_dataset
    builder.download_and_prepare(download_config=download_config)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 287, in download_and_prepare
    download_config=download_config)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 948, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 816, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/dataset_builder.py", line 974, in _prepare_split
    example = self.info.features.encode_example(record)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/features/features_dict.py", line 168, in encode_example
    in utils.zip_dict(self._feature_dict, example_dict)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/features/features_dict.py", line 167, in <dictcomp>
    for k, (feature, example_value)
  File "/Users/chriszhou/anaconda/envs/py37/lib/python3.7/site-packages/tensorflow_datasets/core/features/feature.py", line 480, in encode_example
    example_data = np.array(example_data, dtype=np_dtype)
TypeError: __array__() takes 1 positional argument but 2 were given
```

### CODE REVIEW

**Comment by chriszhou0916** [comment]
@googlebot I signed it!

**Comment by leohu6** [comment]
@googlebot I signed it!

**Comment by leohu6** [comment]
@googlebot I fixed it.

**Comment by chriszhou0916** [comment]
@googlebot I fixed it.

**Comment by leohu6** [comment]
@googlebot I signed it!

**Comment by leohu6** [comment]
@googlebot I fixed it.

**Comment by leohu6** [comment]
@googlebot I fixed it.

**Comment by leohu6** [comment]
@googlebot I signed it!

**Comment by leohu6** [comment]
@googlebot I fixed it.

**Comment by chriszhou0916** [comment]
@googlebot I fixed it.

**Comment by Ouwen** [comment]
@chriszhou0916 @leohu6 

This should probably be renamed
https://github.com/tensorflow/datasets/blob/2a64ccbebee94a27777bcf1579506b9c48d5367c/tensorflow_datasets/image/spine_web.py#L38-L43

`cobb_angles` should be `labels`
or 
`labels` should be `cobb_angles`

**Comment by Ouwen** [comment]
@chriszhou0916 it looks like your commit history uses a different author than your own account. You'll likely need to fix this for the cla bot to work. The simplest way to do this is just to squash your commits down to a single commit.

`git checkout -b "branch_fix"` to make a new branch from your current repo

**Pull request closed without merging**
