### PR TITLE
Adding wiki_auto dataset for text simplification task. This is also a task for the GEM: Natural Language Generation, Evaluation and Metrics workshop to be held at ACL 2021.

### PR DESCRIPTION
**Pull request by ddhruvkr**
# Add Dataset

* Dataset Name: wiki_auto ([link](https://github.com/chaojiang06/wiki-auto))
* Issue Reference: None
* `dataset_info.json` Gist: None
  
## Description

WikiAuto provides a set of aligned sentences from English Wikipedia and Simple English Wikipedia as a resource to train sentence simplification systems.

The authors first crowd-sourced a set of manual alignments between sentences in a subset of the Simple English Wikipedia and their corresponding versions in English Wikipedia (this corresponds to the 'manual' config in this version of the dataset), then trained a neural CRF system to predict these alignments.

The trained alignment prediction model was then applied to the other articles in Simple English Wikipedia with an English counterpart to create a larger corpus of aligned sentences (corresponding to the auto and auto_acl configs here).
  
## Checklist
* [x] Address all TODO's
* [x] Add alphabetized import to subdirectory's `__init__.py`
* [x] Run `download_and_prepare` successfully
* [x] Add [checksums file](https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally)
* [x] Properly cite in `BibTeX` format
* [x] Add passing test(s)
* [x] Add test data
* [x] If using additional dependencies (e.g. `scipy`), use [lazy_imports](https://www.tensorflow.org/datasets/add_dataset#extra_dependencies) (if applicable)
* [x] Add data generation script (if applicable)
* [x] [Lint](https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style) code

### CODE REVIEW

**Review by NikhilBartwal — COMMENTED** [review]
@ddhruvkr Thank you for the contribution. @Conchylicultor The dataset was successfully generated, tested and checked for linting!

**Review by NikhilBartwal — APPROVED** [review]

**Comment by ddhruvkr** [comment]
@NikhilBartwal I have updated the pull request to resolve the conflict that arose as the py2 legacy init was removed. Additionally, updated the dataset based on the changes made by the WikiAuto paper authors. Could you please merge this if everything looks fine?

**Comment by ddhruvkr** [comment]
@NikhilBartwal @Conchylicultor Any updates?

**Comment by ccl-core** [comment]
Thank you, @ddhruvkr for your contribution! Apologies for the delay, we are getting your dataset merged very soon!

**Pull request merged**
