### PR TITLE
Cleanup script to delete older dataset versions

### PR DESCRIPTION
**Pull request by ManishAradwad**
## Description
Issue : #1534  

Hello @Conchylicultor the script you've provided is returning an empty generator object. I tried running `tfds.list_builders()` in cleanup_metadata.py and it is returning the list of all available datasets, but when I run `iter_dataset_full_names` from registered.py I'm still getting empty object. Could you plz help?

### CODE REVIEW

**Comment by Conchylicultor** [comment]
To debug this, you could try to print the values, for instance what is the content of `_DATASET_REGISTRY` ? Is `list_builder()` working properly ? And then try to progressively find the source of the issue. If `list_builder()`is working but not `iter_dataset_full_names`, you can start from the `list_builder` code and gradually add feature until localising the issue.

**Comment by rohanreddych** [comment]
@Conchylicultor the _DATASET_REGISTRY is empty `_DATASET_REGISTRY = {}` is there any init script which initializes this dict because there is no function in this file which initializes it

**Comment by Conchylicultor** [comment]
I'm talking about printing `_DATASET_REGISTRY` inside the `iter_dataset_full_names` function, which is the function you're trying to debug.
Datasets are automcatically added to `_DATASET_REGISTRY` when they are imported, in your case in `import tensorflow_datasets as tfds`. If `list_builder` is not empty, then neither should `_DATASET_REGISTRY`.

**Comment by ManishAradwad** [comment]
@Conchylicultor Actually, `list_builder` is also retuning an empty set.
I tried importing `tfds` in `registered.py` and then printing `_DATASET_REGISTRY` and `list_builders()`, they both are empty. 
I saw there is a function `__new__` under `RegisteredDataset` class in registered.py which is providing values for `_DATASET_REGISTRY`. Could it be of some help??

**Comment by Conchylicultor** [comment]
@ManishAradwad the datasets are added on import. So importing TFDS (`import tensorflow_datasets as tfds`) should import all datasets.

Is `tfds.image.mnist.MNIST()` available ? If so, it should be registered in the `_DATASET_REGISTRY`, otherwise, you should investigate why it doesn't get imported.

**Comment by Conchylicultor** [comment]
> I tried importing tfds in registered.py

You should import tfds inside your `scripts/cleanup_metadata.py`. Not inside `registered.py`.

And you should test the script through executing `cleanup_metadata.py`. And check there that the `list_builder` & cie are not empty.

**Comment by ManishAradwad** [comment]
Yes, actually I've done the exact same thing. I imported `tfds` in `registered.py` to see if `_DATASET_REGISTRY` updates or not after running only `registered.py`(and eventually it doesn't).

> Is `tfds.image.mnist.MNIST()` available ? If so, it should be added in the `_DATASET_REGISTRY`, otherwise, you should investigate why it doesn't get imported.

I'll try doing this.

**Comment by Conchylicultor** [comment]
Hey @ManishAradwad , any updates on this ?

**Comment by ManishAradwad** [comment]
@Conchylicultor I tried using `tfds.image.mnist.MNIST()`, `cleanup_metadata.py` runs fine without any errors but I'm still getting empty `_DATASET_REGISTRY` and `list_builders()`

**Comment by ManishAradwad** [comment]
To make sure I'm doing everything correctly here's the list of things I'm doing:
- In `registered.py`:
Added 3 functions - `_get_all_versions` , `iter_dataset_full_names` and `print_dataset_registry`(prints `_DATASET_REGISTRY` and `list_builders()`)

- In `cleanup_metadata.py`:
Imported `tfds`
Imported `registered.py`
Called `tfds.image.mnist.MNIST()`
Printed `iter_dataset_full_names` output as a list
Called `print_dataset_registry`

**Comment by Conchylicultor** [comment]
Can anyone help on this ?

**Comment by Conchylicultor** [comment]
@ManishAradwad you could look at the `download_and_prepare.py` script and start from there to see how this is done. This script correctly loads all dataset list.

**Comment by ManishAradwad** [comment]
@Conchylicultor I tried going through `download_and_prepare.py` but couldn't get how to fetch the versions of all datasets. 

Also regarding our previous approach, is it possible to use `iter_dataset_full_names` like `tfds.list_builders()`(i.e. as `tfds.iter_dataset_full_names()`)?

I tried this approach by adding `from tensorflow_datasets.core.registered import iter_dataset_full_names` in `public_api.py` and running `tfds.iter_dataset_full_names()`. But I'm still getting no attribute error:
```AttributeError: module 'tensorflow_datasets' has no attribute 'iter_dataset_full_names'```  
Could you plz help?

**Comment by vijayphoenix** [comment]
> Can anyone help on this?

@ManishAradwad If you want you can collaborate with #1730 as you both are working on the same issue.

**Comment by Eshan-Agarwal** [comment]
@vijayphoenix  Its almost finish just have to change few things I don't think this have any work remaining wotk.

**Pull request closed without merging**
