### PR TITLE
Add Czech Restaurants dataset

### PR DESCRIPTION
**Pull request by tuetschek**
# Add Dataset

* Dataset Name: Czech Restaurants
* `dataset_info.json` Gist: https://gist.github.com/tuetschek/b3e66b95b4411247811783318d17345a
  
## Description

Czech data-to-text dataset in the restaurant domain. The input meaning representations contain a dialogue act type (inform, confirm etc.), slots (food, area, etc.) and their values. It originated as a translation of  the English San Francisco Restaurants dataset by Wen et al. (2015).

To be used in the [GEM shared task](https://gem-benchmark.github.io/).
  
## Checklist
* [ ] Address all TODO's
* [x] Add alphabetized import to subdirectory's `__init__.py`
* [ ] Run `download_and_prepare` successfully
* [x] Add [checksums file](https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally)
* [x] Properly cite in `BibTeX` format
* [x] Add passing test(s)
* [x] Add test data
* [ ] If using additional dependencies (e.g. `scipy`), use [lazy_imports](https://www.tensorflow.org/datasets/add_dataset#extra_dependencies) (if applicable)
* [ ] Add data generation script (if applicable)
* [ ] [Lint](https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style) code

### CODE REVIEW

**Comment by tuetschek** [comment]
@googlebot I signed it!

**Review by NikhilBartwal — CHANGES_REQUESTED** [review]
Hey @tuetschek, Thank you for contributing to TFDS!

Although the dataset scripts looks fine at glance, but TFDS has now adopted a newer folder model (i.e a separate folder for each dataset containing the generation and test script, along with the checksums and examples). You can find more about it [here](https://www.tensorflow.org/datasets/add_dataset#default_template_tfds_new)

It would be great if you could re-structure the dataset according to the steps as outlined in the link above.

**Comment by tuetschek** [comment]
Hi @NikhilBartwal , thanks for checking! I've tried to restructure the files – please let me know if you need me to change anything more.

**Comment by ccl-core** [comment]
Hello @tuetschek , thank you for your contribution! It looks like your branch has conflicts that mist be resolved.

To bring it bring it up to date, you typically require to run:
```
# On your feature branch
git fetch origin master
git rebase origin/master
```

**Comment by ccl-core** [comment]
Thank you, @tuetschek  for your contribution! Apologies for the delay, we are getting your dataset merged very soon!

**Pull request merged**
