### PR TITLE
Added HIGGS dataset

### PR DESCRIPTION
**Pull request by ChanchalKumarMaji**
`dataset request` #330 
@rsepassi @Conchylicultor @cyfra please review.

### CODE REVIEW

**Comment by cyfra** [comment]
Nice job. Preparing for merge.

**Comment by ChanchalKumarMaji** [comment]
@cyfra just one thing to mention here, I think a new style has been introduced to include checksum files. How to add that file?

**Comment by cyfra** [comment]
Please see the section in the 'add_dataset.md' file:
https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md#2-run-download_and_prepare-locally

**Comment by ChanchalKumarMaji** [comment]
@cyfra I have added the `higgs.txt` checksum file. Thanks.

**Pull request merged**
