### PR TITLE
Add initial unit test and test data

### PR DESCRIPTION
**Pull request by tonanhngo**
Test data is created separately from the ezDI dataset
Unit test is derived from the CommonVoice unit test, have not tried running yet
Need to create the main class before running

### CODE REVIEW

**Comment by tonanhngo** [comment]
The ezDI dataset is a high quality curated medical dictation dataset available from https://www.ezdi.com/open-datasets
This is a special domain data that can be trained on top of a general conversation audio dataset such as CommonVoice.
The main class for this dataset is being added next.

**Comment by Conchylicultor** [comment]
Thanks for your contribution.

* In order to submit to this repository, you need to first sign the Contributor License Agreement (see previous googlebot message)
* Where is the dataset associated with those tests ? Dataset and tests have to be submitted at the same time.

**Comment by us** [comment]
@cyfra @Conchylicultor we can close this.

**Comment by cyfra** [comment]
Hey @tonanhngo - do you plan to work more on this dataset?
If yes, please send both dataset and the test in a single PR.

I'll close this one for now (as it was not active for 3 months) - please create the new PR whenever you're ready.

**Pull request closed without merging**
