### PR TITLE
Add UrlInfo.filename

### PR DESCRIPTION
**Pull request by harsh020**
## Part 1 of 2 | Add UrlInfo.filename in checksums

PR for issue #2422 

Tasks - 

* [x] Make UrlInfo a dataclass.
* [x] Remove magic methods.
* [x] Add `filename` attribute to `UrlInfo` class.
* [x] Update functions in `checksums` to use `UrlInfo.filename`.
* [x] Update modules using `UrlInfo` class accordingly.

### CODE REVIEW

**Comment by harsh020** [comment]
@googlebot I signed it!

**Comment by harsh020** [comment]
@Conchylicultor Now I'm working on updating the modules that are failing on running test. Will update it as soon as I'm done.

Thanks.

**Review by Conchylicultor — CHANGES_REQUESTED** [review]
Thank you. This looks good.
As a next step, `UrliInfo()` statements in `core/download/` should now be updated. You can run the unittest for :

```sh
pytest tensorflow_datasets/core/download
```

**Review by Conchylicultor — APPROVED** [review]
Thank you for the update.
It seems that some unittests where still failing but I fixed remaining usages of UrlInfo (e.g. in `_sync_file_copy`), so you're all good.

**Comment by harsh020** [comment]
@Conchylicultor Thanks a lot. This is odd, when I run the test independently just for `core/download` then I don't get any test failures, but if I run it for `core` then I do get failures for tests in `core/downloads`. Maybe thats why I missed out some fixes.

**Comment by harsh020** [comment]
@Conchylicultor, The `_sync_file_copy` is in `downloader.py`, why didn't I receive any test failure from it when I ran tests within `core/downloads`. Is it not covered by test?

Should I find and make the required changes (or where can I pull your changes from)? 

Thanks.

**Comment by Conchylicultor** [comment]
@harsh020 yes, our tests coverages are not 100%, but I think `download_manger_test.py` was also failing.

No worries, I fixed those issues internally. It should be good now.

**Pull request merged**
