### PR TITLE
Visualization support for images when as_supervised is set true

### LINKED ISSUE #1575: [GSoC] Add `as_supervised=True` compatibility for `tfds.show_examples`
It would be nice if `tfds.show_examples` was working with `as_supervised=True`. Currently it raise a not supported error:

```python
ds, ds_info = tfds.load('mnist', split='train', as_supervised=True)
tfds.show_examples(ds_info, ds)
```
Changes should only affect the `show_examples` function, so it should be fairly simple.

### PR DESCRIPTION
**Pull request by vijayphoenix**
Fix #1575

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you very much. This would works however the implementation do not seem really scalable. For instance, every time someone want to add a new visualization capability, he/she would be forced to add `if is_supervised else` everywhere in his code.
Could you try to refactor this to make this more generic ?

**Comment by vijayphoenix** [comment]
@Conchylicultor yeah, actually I was thinking of making a complete Visualization class which would work for all kinds of image datasets (for now, maybe extend this to other type datasets later).

Basically, this approach will address both  #1528 and #1575 at the same time.
But this will require a good amount of time, so this PR was just a temporary fix

**Comment by Conchylicultor** [comment]
@vijayphoenix, yes, having a more flexible visualization looks good! Thank you for looking into this.

**Comment by vijayphoenix** [comment]
@Conchylicultor Please review the changes.
Thank you

**Comment by vijayphoenix** [comment]
@Conchylicultor Please review the changes.
Thank you

**Pull request closed without merging**
