### PR TITLE
Added Dep of Tensorflow_io.lmdb  to LSUN

### LINKED ISSUE #34: Rm dep on tf.contrib.data.LMDBDataset for TF 2.0
tf.contrib.data.LMDBDataset will not make it to TF2. It may be moving to a new repo/package. If/when that happens, we should switch to it.

Part of #31 (TF 2.0 support)

### PR DESCRIPTION
**Pull request by ParthS007**
Fixes #34 
@rsepassi @Conchylicultor @cyfra Please review. Thanks :)

### CODE REVIEW

**Comment by ParthS007** [comment]
@tfds-copybara Can you please tell why Kokoro is failing?

**Comment by us** [comment]
Kokoro run test codes using different versions of TF and python. Versions earlier than TF 2.0 give errors. So Kokoro failed. 
You need to check version of TF and if version greater than 2.0 you can call tf_io otherwise you need to call old structure.

**Comment by ParthS007** [comment]
> You need to check version of TF and if version greater than 2.0 you can call tf_io otherwise you need to call old structure.

@us How can I do it?

**Comment by us** [comment]
You can check `core/tf_combat.py` to compatibility tf versions.

**Comment by us** [comment]
@ParthS007 hey did you check it ?

**Pull request closed without merging**
