### PR TITLE
added support show_examples for translate data

### PR DESCRIPTION
**Pull request by dhirensr**
related to https://github.com/tensorflow/datasets/issues/1528

added support show_examples for translate type datasets

https://colab.research.google.com/drive/1LDXsE2tAxbn8qnhqpxUnXVpzltpSiYts

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you for your contribution, however, I'm not really sure what that users really want to have show_examples return a list of string.
Users can already get this using `list(tfds.as_numpy(ds.take(5)))`, so it's not clear to me what advantage this would bring vs the added complexity.
Unless we came out with a nice way of formatting the text I think we should focus on images types first (like object detection).

**Comment by dhirensr** [comment]
@Conchylicultor : so for now I will send for the image datasets then like object detection or 2 image side by side

**Comment by Conchylicultor** [comment]
Sounds good!

**Comment by Conchylicultor** [comment]
Closing this as the user can already get the same feature with `list(tfds.as_numpy(ds.take(5)))`.
Note that I recently refactored the visualization to make it easier to add new extensions, in case you'll like to add new visualisation types.

**Pull request closed without merging**
