### PR TITLE
Update URL of the dataset Plant Village

### PR DESCRIPTION
**Pull request by davequinta**
The url in the file, was throwing  error 404, and when you try to access it, it says Page not found The page you are looking for was not found, actually its a different URL from the TF docs (https://www.tensorflow.org/datasets/catalog/plant_village), I've added the correct one from https://data.mendeley.com/datasets/tywbtsjrjv/1

# Add Dataset

* Dataset Name: <Plant_Village>
* Issue Reference: https://github.com/tensorflow/tensorflow/issues/41051

  
## Description
It's and update of the URL

### CODE REVIEW

**Comment by davequinta** [comment]
@googlebot I signed it!

**Comment by davequinta** [comment]
@Conchylicultor  oh no, sorry! I made a mistake in the PR, its not **ADD DATASET** persé, it's modify the url

**Comment by Conchylicultor** [comment]
> @Conchylicultor oh no, sorry! I made a mistake in the PR, its not **ADD DATASET** persé, it's modify the url

You updated the downloaded URL, so checksums should be updated to match this change.
Could you regenerate the new checksums by running `--register_checksums` following https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally ?

**Comment by Conchylicultor** [comment]
Hey @davequinta. Any update on this ?

**Comment by vijayphoenix** [comment]
Added updated checksums in https://github.com/tensorflow/datasets/pull/2229

**Pull request closed without merging**
