### PR TITLE
Update tfrecords_reader.py

### PR DESCRIPTION
**Pull request by abhinavsp0730**
Raised an error for the depreciation of the Legacy split API.

### CODE REVIEW

**Comment by abhinavsp0730** [comment]
Hey, @Conchylicultor kindly review it.

**Comment by Conchylicultor** [comment]
Could you add a test for this ?
Also you should try to make the check more generic, rather than special-case for the specific 'train' set. For instance what if the user use legacy split API with test set ? Your check won't catch it.

**Comment by abhinavsp0730** [comment]
Hey, I'll try to make it Genric. And then I'll to send a PR by today itself.

**Comment by Conchylicultor** [comment]
Any updates on this ?

**Comment by abhinavsp0730** [comment]
Hey, @Conchylicultor due to covid-19 our college's shut down and we've to move from our hostel to home. Due to this I've forget about this PR. Now everything is stable. Will come with the updated code by tomorrow.
Thanks.

**Comment by abhinavsp0730** [comment]
Thanks I'm closing this, and reopen this PR after some days, if i'm able to work in it.

**Pull request closed without merging**
