### PR TITLE
Add instructions on using PR template

### PR DESCRIPTION
**Pull request by WilliamHYZhang**
Updated the instructions to include how to use the newly added pr template.

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thanks, could you just try to create a dummy PR, just to make sure the instructions works correctly ?

**Comment by WilliamHYZhang** [comment]
@Conchylicultor please see #1388

**Comment by Conchylicultor** [comment]
Thanks for the follow up, merging this soon.

**Comment by Conchylicultor** [comment]
After discussion internally, we decided to make your template the default template for all PR. This way, no instructions are required. We decided this as the vast majority of our PR are datasets.
I renamed your file `.github/pull_request_template.md` in https://github.com/tensorflow/datasets/commit/32ece0f45aba28e339bd44ddbe6500f71a0ce5e2.

Thanks again for helping us.

**Comment by WilliamHYZhang** [comment]
That sounds great, happy to help!

**Comment by WilliamHYZhang** [comment]
@Conchylicultor I updated to just include mention of using the template and how to use the checklist.

**Comment by Mbah-Javis** [comment]
This is amazing :) @WilliamHYZhang pls will u mind resolving the conflicts :)

**Comment by WilliamHYZhang** [comment]
Seems like the copybara already merged this :+1: Closing now :)

**Pull request closed without merging**
