### PR TITLE
Update scientific_papers dataset links and checksums

### LINKED ISSUE #1404: Bad CRC-32 when extracting scientific_papers
**Short description**
I have been using the `tfds.load` function to download and split many other summarization datasets, `billsum`, `cnn_dailymail`, and `big_patent`, without any problem. 
When trying to do so with `scientific_papers`, I ran into Bad CRC-32 error when trying to load scientific_paper dataset in the extraction step. However, I could manually unzip the file without any CRC-32 error. This happens to both `arxiv` and `pubmed` under `scientific_papers`. This might be a bug with Python 3.6's zip extractor. 

**Environment information**
* Operating System: Ubuntu Linux 18.04
* Python version: 3.6 (Ubuntu system's) 
* `tensorflow-datasets`/`tfds-nightly` version: `tensorflow-datasets 1.3.2`
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: `tensorflow-2.0.0`

**Reproduction instructions**

```
import tensorflow_datasets as tfds
    _ = tfds.load("scientific_papers")

```

**Link to logs**
[traceback.log](https://github.com/tensorflow/datasets/files/4083729/traceback.log)

**Expected behavior**
There shouldn't be errors but messages that the dataset has been successfully extracted, shuffled and split.

### PR DESCRIPTION
**Pull request by Eshan-Agarwal**
Fixes #1404 

@Conchylicultor  Updates `scientific_papers.py` and `scientific_papers.txt` files to new correct URLs. Now it will extracting `train.txt` with no errors. Please have a look.

### CODE REVIEW

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Why above checks are fails and after checking these checks its showing test failure for `wmt19_test.py`.

**Comment by Conchylicultor** [comment]
Tests are failing because of https://github.com/tensorflow/datasets/issues/1638

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Is this PR related to it ? So if I can make changes in it.

**Comment by Conchylicultor** [comment]
This isn't related. As tests are currently broken, it will fail for all PR

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Thanks for your review. I am working on it, Tried with different version of python also like 3.5, 3.6, 3.7, 3.8 got same error as i mentioned and also tried it on WSL but not able to reproduce the error described by you instead got different. So also create other environment and reinstall dependencies but still no luck.

**Pull request merged**
