### PR TITLE
Added condition that fixes downloading error

### PR DESCRIPTION
**Pull request by kyscg**
While downloading from Kaggle, I noticed that empty lines were giving rise to errors and I fixed it with a simple if statement.

### CODE REVIEW

**Comment by kyscg** [comment]
Review @cyfra @Conchylicultor ???

**Comment by kyscg** [comment]
Please review and let me know if there any changes @cyfra @Conchylicultor

**Comment by us** [comment]
#165 It has already been repaired.

**Comment by kyscg** [comment]
Cool, thanks for the heads up

**Pull request closed without merging**
