### PR TITLE
Update checksums of oxford_flowers102 and dtd datasets

### LINKED ISSUE #1977: Checksums for oxford_flowers102 changed
**Short description**
The checksum for `oxford_flowers102` changed recently which breaks downloading of the dataset.

**Environment information**
* Operating System: macOS
* Python version: 3.7
* `tensorflow-datasets`/`tfds-nightly` version: 3.1.0
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 2.2.0rc3

**Reproduction instructions**

```
rm -r ~/tensorflow_datasets/oxford_flowers102/
rm -r ~/tensorflow_datasets/downloads
```
```python
tfds.load("oxford_flowers102", split="train")
```

**Link to logs**
```
Artifact https://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz, downloaded to ~/tensorflow_datasets/downloads/robots.ox.ac.uk_vgg_flowers_102_102flowersoWedSp98maBn1wypsDib6T-q2NVbO40fwvTflmPmQpY.tgz.tmp.9496e46fb0ed404fa5b339ba8c39a725/102flowers.tgz, has wrong checksum. This might indicate:
 * The website may be down (e.g. returned a 503 status code). Please check the url.
 * For Google Drive URLs, try again later as Drive sometimes rejects downloads when too many people access the same URL. See https://github.com/tensorflow/datasets/issues/1482
 * The original datasets files may have been updated. In this case the TFDS dataset builder should be updated to use the new files and checksums. Sorry about that. Please open an issue or send us a PR with a fix.
 * If you're adding a new dataset, don't forget to register the checksums as explained in: https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally
```

**Expected behavior**
Checksums should match and extraction would succeed.

### PR DESCRIPTION
**Pull request by vijayphoenix**
Fix #1977 

oxford_flowers102 : [dataset_info](https://gist.github.com/vijayphoenix/e8da593cce3498739439dbbf01c785e3)
dtd: [dataset_info](https://gist.github.com/vijayphoenix/3d5719db2ef8fb2e544ea088a7c4d32f)

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you for updating this.
This sounds strange that the checksums has changed. It means someone has updated the files. Do we know why ? There is a risk that the data has changed.

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  VGGFace2 and VoxCeleb datasets is changed with some new examples see [here](https://www.robots.ox.ac.uk/~vgg/data/vgg_face/)

**Comment by Conchylicultor** [comment]
Where do you see the date at which the dataset has been updated ?

**Comment by vijayphoenix** [comment]
@Conchylicultor I couldn't find anything that mentions some change in the data recently.
And its rather unusual for all the datasets to get updated at the same time.

**Comment by Eshan-Agarwal** [comment]
Dates are not mentioned it look like they 

> Where do you see the date at which the dataset has been updated ?

Its just show `NEW `dates are not mentioned so probably datasets are recently update but @vijayphoenix is right all datasets are together get updated is strange

**Comment by Conchylicultor** [comment]
In all the archives, it seems that the size is smaller than before. That may mean they have recreated the archives with a better compression algorithm

**Pull request merged**
