### PR TITLE
Fixed quickdraw_bitmap URLs in docs

### PR DESCRIPTION
**Pull request by tfujiwar**
The URLs of `quickdraw_bitmap` dataset in document was not displayed correctly.

### CODE REVIEW

**Comment by ChanchalKumarMaji** [comment]
Make sure that you generated `datasets.md` using [document_datasets.py](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/scripts/document_datasets.py).

**Comment by tfujiwar** [comment]
@ChanchalKumarMaji 
Only the updated section in `datasets.md` was generated using `document_datasets.py` by specifying the name of the dataset in the script.

Because I failed to execute `document_datasets.py` with the error below. Should I fix this first?
```
...
I0530 20:22:02.297413 4781708736 dataset_info.py:398] Loading info from GCS for super_glue/copa/0.0.2
E0530 20:22:03.379710 4781708736 registered.py:171] Failed to construct dataset super_glue
Traceback (most recent call last):
...
ValueError: Trying to overwrite already defined ClassLabel names. Previous: ['choice1', 'choice2'] , new: ['False', 'True']
```

**Comment by ChanchalKumarMaji** [comment]
Okk, if the results are in accordance with your expectations then you need not generate the whole file. They will be updated by the community members.

**Comment by Conchylicultor** [comment]
Thanks for fixing this. Note that the docs will automatically updated, so no worries about that.
Thanks for reporting the error, it is due to a mismatch between our GCS version and code.

**Pull request merged**
