### PR TITLE
Add gsutil support to downloader.

### PR DESCRIPTION
**Pull request by us**
This is just the draft I wrote to better explain my mind. We can discuss on this code to better understand.

### CODE REVIEW

**Comment by ChanchalKumarMaji** [comment]
Any `test_file` for this ?

**Comment by us** [comment]
I'll add after the after confirmation of this feature.

**Comment by pierrot0** [comment]
Thanks!

Overall, this looks like what we want.
We would want however to make sure the gsutil binary is available (or otherwise fall back on standard url handling).

Have you checked kaggle doesn't provide an API instead of using external binary?
Is the usage similar on windows?

**Comment by Conchylicultor** [comment]
Clsoing this as the PR seems abandoned. Please re-open the PR if you want to continue this

**Pull request closed without merging**
