### PR TITLE
clean up dataset code

### PR DESCRIPTION
**Pull request by SuryashankarDas**
This PR refers issue #2460 
Dataset is generated without any problems.
dataset_info.json: https://gist.github.com/SuryashankarDas/48a971a800eb03fd0363d416c206a198

### CODE REVIEW

**Review by Conchylicultor — APPROVED** [review]
Thank you

**Comment by SuryashankarDas** [comment]
added a commit for spoken_digit too.
dataset_info.json: https://gist.github.com/SuryashankarDas/cf3af361e347ac7ec786490243520e34

**Comment by SuryashankarDas** [comment]
added commit for oxford_iiit_pet dataset.
dataset_info.json: https://gist.github.com/SuryashankarDas/d3258b8c1471043249f8409b27d770be

**Comment by Conchylicultor** [comment]
Please open a new PR with the last examples. Once I approved the PR, it means it was imported internally, so new changes won't be applied.

**Comment by SuryashankarDas** [comment]
Oh ok. I had no idea about that.

**Pull request merged**
