### PR TITLE
Update celeba.py

### PR DESCRIPTION
**Pull request by aayu04**

### CODE REVIEW

**Comment by aayu04** [comment]
I signed it!

**Comment by ParthS007** [comment]
@aayu04 I have already made a PR solving this Issue. You can take up any other Issue as many Issues are unassigned here. I hope you understand.

Thanks

**Comment by aayu04** [comment]
Hey parth i understand that. Actually i am newbie to these sort of things
and want to contribute anyhow possible. Why don't we collab for this issue?

**Comment by ParthS007** [comment]
@aayu04 You should have commented on the Issue. I am almost done working on this Issue and we can surely collab on other Issues. :+1:

**Comment by rsepassi** [comment]
Thanks so much for contributing @aayu04 but closing in favor of #152 as @ParthS007 did start work beforehand. Let's find another issue you can contribute on! Take a look at the currently [unassigned issues](https://github.com/tensorflow/datasets/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee).

**Pull request closed without merging**
