### PR TITLE
Add Malaria dataset.

### PR DESCRIPTION
**Pull request by us**
Repaired and sent to continue this pr. #481

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Could you re-post `@googlebot I consent.` to reactivate the cla ? It seems that google-bot has issue authenticating you.

**Comment by us** [comment]
@googlebot I consent.

**Comment by us** [comment]
@Conchylicultor I think it's want to also SoumyadeepJana post, because of his commits.

**Comment by us** [comment]
@cyfra change also this cla label.

**Comment by us** [comment]
@Conchylicultor @cyfra ping.

**Pull request merged**
