### PR TITLE
Minor corrections in datasets to able to use in windows 

### PR DESCRIPTION
**Pull request by Eshan-Agarwal**
similar to #1888

### CODE REVIEW

**Comment by vijayphoenix** [comment]
@Eshan-Agarwal please see https://github.com/tensorflow/datasets/pull/1892#issuecomment-615360033
to fix caltech_birds

**Comment by Eshan-Agarwal** [comment]
> @Eshan-Agarwal please see [#1892 (comment)](https://github.com/tensorflow/datasets/pull/1892#issuecomment-615360033)
> to fix caltech_birds

@vijayphoenix Thanks for suggestions I also tried this its not escaping output is this , are you tried this?
`'CUB_200_2011\\images\x1d.Purple_Finch\\Purple_Finch_0091_27425.jpg'`

**Comment by vijayphoenix** [comment]
@Eshan-Agarwal I have not used windows on my laptop for ages, so I am afraid to start it :sweat_smile: 
raw_strings should work fine though
```
>>> print(r'\023')
\023
```

**Comment by Eshan-Agarwal** [comment]
> @Eshan-Agarwal I have not used windows on my laptop for ages, so I am afraid to start it 😅
> raw_strings should work fine though
> 
> ```
> >>> print(r'\023')
> \023
> ```
😅 yeah raw string works but in our case in `caltech_birds` dataset fnames come from archive which we cannot take input as raw string as I know if you have solution to this suggest please

**Comment by vijayphoenix** [comment]
@Eshan-Agarwal could u please create a new issue to keep a track of `caltech_birds` bug and also do add the stack trace.
Thank you

**Comment by Eshan-Agarwal** [comment]
sure, I was also think of it

**Pull request merged**
