### PR TITLE
Adding asset dataset for text simplification task. This is also a task for the GEM: Natural Language Generation, Evaluation and Metrics workshop to be held at ACL 2021.

### PR DESCRIPTION
**Pull request by ddhruvkr**
# Add Dataset

* Dataset Name: wiki_auto ([link](https://github.com/chaojiang06/wiki-auto))
* Issue Reference: None
* `dataset_info.json` Gist: None
  
## Description

ASSET is a dataset for evaluating Sentence Simplification systems with multiple rewriting transformations, as described in "ASSET: A Dataset for Tuning and Evaluation of Sentence Simplification Models with Multiple Rewriting Transformations". The corpus is composed of 2000 validation and 359 test original sentences that were each simplified 10 times by different annotators. The corpus also contains human judgments of meaning preservation, fluency and simplicity for the outputs of several automatic text simplification systems.
  
## Checklist
* [x] Address all TODO's
* [x] Add alphabetized import to subdirectory's `__init__.py`
* [x] Run `download_and_prepare` successfully
* [x] Add [checksums file](https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally)
* [x] Properly cite in `BibTeX` format
* [x] Add passing test(s)
* [x] Add test data
* [x] If using additional dependencies (e.g. `scipy`), use [lazy_imports](https://www.tensorflow.org/datasets/add_dataset#extra_dependencies) (if applicable)
* [x] Add data generation script (if applicable)
* [x] [Lint](https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style) code

### CODE REVIEW

**Review by NikhilBartwal — APPROVED** [review]
@ddhruvkr The dataset is generated and tested successfully. Thank you!

**Comment by ddhruvkr** [comment]
@NikhilBartwal I have updated the pull request to resolve the conflict that arose as the py2 legacy __init__ was removed. Could you please merge this if everything looks fine?

**Comment by NikhilBartwal** [comment]
@Conchylicultor It would be great if you could have a look at this.

**Comment by ddhruvkr** [comment]
@NikhilBartwal @Conchylicultor Any updates?

**Comment by ccl-core** [comment]
Thank you, @ddhruvkr for your contribution! Apologies for the delay, we are getting your dataset merged very soon!

**Pull request merged**
