### PR TITLE
Invert ds, ds_info argument orders for tfds.show_examples

### PR DESCRIPTION
**Pull request by tfds-copybara**
Invert ds, ds_info argument orders for tfds.show_examples

### CODE REVIEW

**Comment by Eshan-Agarwal** [comment]
Also I think we have to use `data_name` and `data_info` because of `pylint `

**Comment by Conchylicultor** [comment]
> Also I think we have to use data_name and data_info because of pylint

I'm not sure what you mean by this. Could you provide more context ?

**Comment by Eshan-Agarwal** [comment]
Sure, when running pylint, I got this errors

> Argument name "ds" doesn't conform to snake_case naming style (invalid-name)
Variable name "c" doesn't conform to snake_case naming style (invalid-name)
Argument name "ds" doesn't conform to snake_case naming style (invalid-name)

**Comment by Conchylicultor** [comment]
@Eshan-Agarwal this sounds like a bug from `pylint` as `ds` is a perfectly valid name.

**Pull request merged**
