### PR TITLE
Improve Kaggle API documentation and error msgs

### PR DESCRIPTION
**Pull request by vijayphoenix**
- Improve Function docstring 
- Better error msg

### CODE REVIEW

**Comment by sharanramjee** [comment]
Looks good to me!

**Comment by sharanramjee** [comment]
Can you add documentation on how to use the download_kaggle_data() to the [Adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md) documentation too? @vijayphoenix

**Comment by sharanramjee** [comment]
You could add information to the [Adding a dataset](https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md) about how the copyright agreement (first 16 commented lines in the .py files) is automatically added as well.

**Comment by vijayphoenix** [comment]
Merged by https://github.com/tensorflow/datasets/commit/533783930f24da29990baa2b90027c91dae1e346

**Pull request closed without merging**
