### PR TITLE
Optional Builder version

### LINKED ISSUE #2522: `version` should be optional for `BuilderConfig`
The vast majority of `BuilderConfig` are using the same version and are updated at the same time. It is boilerplate to have to specify the version for each config. Instead, the global version should be used by default.

Before:
```py
class MyDataset:
  BUILDER_CONFIGS = [
      tfds.core.BuilderConfig('en', version='1.0.0'),
      tfds.core.BuilderConfig('fr', version='1.0.0'),
  ]
```

After
```py
class MyDataset:
  BUILDER_CONFIGS = [
      tfds.core.BuilderConfig('en'),
      tfds.core.BuilderConfig('fr'),
  ]
  VERSION = tfds.core.Version('1.0.0')
```
If both global and `BuilderConfig` versions are specified, the `BuilderConfig` version should be used.

### PR DESCRIPTION
**Pull request by harsh020**
## PR 1 of 1 | Make Builder version optional and add `ReleaseNotes` property

Fixes #2522 

* [x] Default to `self.VERSION` when `builder.version` is not specified
* [x] Add test for the same
* [x] Add `Release Note` property

### CODE REVIEW

**Comment by harsh020** [comment]
@Conchylicultor Hi, There is an issue, if I make a test as - 
```
 def test_global_vs_builder_version(self):
    global_version = utils.Version("1.0.0")
    builder1_version = utils.Version("1.1.0")
    builder2_version = utils.Version("1.2.0")

    class DummyDatasetV2(DummyDatasetWithConfigs):
      BUILDER_CONFIGS = [
      DummyBuilderConfig(
          name="plus1",
          description="Add 1 to the records",
          version=builder1_version,
          increment=1),
      DummyBuilderConfig(
          name="plus2",
          description="Add 2 to the records",
          version=builder2_version,
          increment=2),
      ]
      VERSION = global_version

    with testing.tmp_dir(self.get_temp_dir()) as tmp_dir:
      builder1 = DummyDatasetV2(data_dir=os.path.join(tmp_dir, 'plus1'))
      builder2 = DummyDatasetV2(data_dir=os.path.join(tmp_dir, 'plus2'))
      self.assertEqual(builder1.version, builder1_version)
      self.assertEqual(builder2.version, builder2_version)
```
then as I'm not specifying `BuilderConfig` for all configs individually, i.e for `builder1` and `builder2`, then due to -
https://github.com/tensorflow/datasets/blob/d83e94ad32eab031367fbe0c1f7d676eba607ae1/tensorflow_datasets/core/dataset_builder.py#L836-L839

the builder2 will also be assigned the `builder_config` of `builder1`.

Can such a case exist?

Thanks

**Comment by harsh020** [comment]
@Conchylicultor Hi, should I push the `ReleseNotes` property in a different PR or would it be fine to do it in this one?

Thanks.

**Comment by Conchylicultor** [comment]
> @Conchylicultor Hi, should I push the ReleaseNotes property in a different PR or would it be fine to do it in this one?

Updating this PR sounds good. thank you!

**Comment by harsh020** [comment]
@Conchylicultor Please do let me know if tests for `release_notes` are required. I have built them for local testing. Will commit if needed.

Thanks.

**Comment by Conchylicultor** [comment]
Thank you for the update. It's always good to have tests.

**Comment by harsh020** [comment]
@Conchylicultor I have made the changes and have also added the tests. Kindly review them whenever possible.

Thanks.

**Comment by Conchylicultor** [comment]
Thank you for your contribution. I've slightly modified your implementation before merging.

**Pull request merged**
