### PR TITLE
Add versions to list builders.

### PR DESCRIPTION
**Pull request by us**
Related issue:  #884

Example of output:
```
[('abstract_reasoning', ['0.0.2']),
 ('amazon_us_reviews', ['0.1.0']),
 ('bair_robot_pushing_small', ['1.0.0', '2.0.0']),
 ('bigearthnet', ['0.0.2']),
 ('binarized_mnist', ['1.0.0']),
 ('binary_alpha_digits', ['1.0.0']),
 ('caltech101', ['1.1.0', '2.0.0', '3.0.0']),
 ('caltech_birds2010', ['0.1.0']),
 ('caltech_birds2011', ['0.1.0']),
 ('cats_vs_dogs', ['2.0.1', '3.0.0', '4.0.0']),
 ('celeb_a', ['0.3.0', '1.0.0', '2.0.0']),
.
.
.
 ('wmt19_translate', ['0.0.3']),
 ('wmt_t2t_translate', ['0.0.1']),
 ('wmt_translate', []),
 ('xnli', ['0.0.1'])]

```

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thanks, but I don't think we want to modify the `tfds.list_builder`. I haven't fully understood what @pierrot0 want.
For me just exposing the available versions to the markdown doc would be enough I think.

**Comment by pierrot0** [comment]
@Conchylicultor: I think we need both.
Exposing version in doc is good for the stable version, but we should have a way of getting that list for head.

Maybe we could have an optional_argument to also return the versions. Would that work for you Etienne?

**Comment by pierrot0** [comment]
@us Thank you Recep, I left a few comments, but overall looks good.

**Comment by Conchylicultor** [comment]
@pierrot0 Where Even if we have a list of all available dataset, I don't think we should have this in `tfds.list_builder`.
 * The current API allows testing like `name in tfds.list_builders()` which I think is a more natural user API than having list_builders to return the tuple (ds_name, version).
* This is also already used multiple times, including outside our repo.
* This do not works well with BuildConfig which can have multiple different versions for the same dataset.

If you really need this, it would make more sense to add this to a new method, which would also properly support builder config.
Where would you plan to use this list for ? Do you want to access it programatically or just a txt file would be enough ?

**Comment by pierrot0** [comment]
As talked offline, let's make a new function.

**Comment by Conchylicultor** [comment]
The [supported.txt](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/metadata/supported.txt) and [missing.txt](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/testing/metadata/missing.txt) files ca be used for this purpose. So closing this.

**Pull request closed without merging**
