### PR TITLE
Fix checksum input

### PR DESCRIPTION
**Pull request by us**
Related issue #769.

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you for fixing this. Can you provide more context to help us avoid this in the future ? Why was a space added in the checksum ? Why was it working before ?

**Comment by ChanchalKumarMaji** [comment]
Some workers are crashing which is causing `kokoro` to fail. What to do ? Here `wikipedia_test.py` is failing. 
This is also an issue on their side as well as I saw many discussions are going on related to this.

**Comment by us** [comment]
The only thing that changes is the version of python. So I thought there was a change that came with the update.

@ChanchalKumarMaji I agree with you. Crash cause is kokoro, testing is okay on my computer.

**Comment by Conchylicultor** [comment]
@us @ChanchalKumarMaji Yes, the crashes are due to pytest-xdist, similar with #765 which make some tests flaky. I don't have a good solution to fix this currently, except re-running Kokoro

**Comment by 20zinnm** [comment]
Can we merge this PR? This issue is very annoying since I develop on a Windows desktop. @us

**Comment by us** [comment]
@20zinnm This pr not merged because tests are not finished. Until this code merges, you can edit this line and compile from the source code.

**Comment by Conchylicultor** [comment]
@20zinnm from what I understand, the issue was the 260 characters limitation on windows. So this fix attempt would not have solved your issue.
So if your issue is solved, can we close this PR ?

**Comment by 20zinnm** [comment]
No, that is a separate issue. This PR resolves the issue of "odd-length
string" while the other resolves the file not found error when creating the
folder.

**Comment by 20zinnm** [comment]
So can this be merged @Conchylicultor ? This PR resolves an issue on windows that prevents any datasets from being downloaded.

@us The kokoro build finished, unless you mean there need to be new tests written for this case?

**Comment by Conchylicultor** [comment]
@20zinnm I would first like to understand why does this bug only appear on windows and where does the extra character comes from.
If the checksum indeed contains an extra space, then the issue is probably located somewhere else in the code. But it is difficult to debug as we do not have windows computer to debug the issue.

**Comment by 20zinnm** [comment]
@Conchylicultor The checksum does not contain an extra space, but rather an extra `\r` at the end of the line.

This is because Python uses `\n` as the separator for reading in by

I just dropped a breakpoint at [`get_dl_fname`](https://github.com/tensorflow/datasets/blob/efcd4ca21e9f1fd7be66e01bbca4ffa1a3b4d873/tensorflow_datasets/core/download/resource.py#L187) and found the value for MNIST to be `440fcabf73cc546fa21475e81ea370265605f56be210a4024d2ca8f203523609\r`.

The `\r` is because when Git checks out code to Windows, by default it replaces `LF` with `CRLF`, and vice versa when pushing. This is why `pip install tensorflow_datasets` does not encounter this error, but `git clone https://github.com/tensorflow/datasets.git && cd datasets && pip install -e .` does, and it's Windows-specific.

A simple solution is to add a `.gitattributes` file to the root of the repository which tells Git to not replace `LF` with `CRLF` for any checksum file.

**Comment by 20zinnm** [comment]
I can submit a PR to resolve this without changing the code. Give me a few minutes.

**Comment by Conchylicultor** [comment]
@20zinnm  Thank you for this detailed explanation. This will be fixed today.

**Comment by Conchylicultor** [comment]
Should be fixed with 76325da.
Thanks @us for the fix. This was the right fix, but I just moved it when file is read to avoid this bug in other places.

**Pull request closed without merging**
