### PR TITLE
Modelnet

### PR DESCRIPTION
**Pull request by jackd**
... this was supposed to just be modelnet10/40 with tri-mesh and point cloud sampling... then I found [this](https://github.com/charlesq34/pointnet2/tree/master/data) and extending it to their sampled data/shapenet parts didn't seem too much more. Apologies for not splitting it up.

One issue I haven't been able to resolve is repeated downloads for different configs of the same dataset. `builder.info.download_checksums` just seem to disappear occasionally between runs. Could be related to [this](https://github.com/tensorflow/datasets/issues/149), but I suspect it's a different issue.

Note sure what the feeling is regarding `volume` submodule - just seemed like a good catch-all for point cloud/mesh/voxels. I suspect there'll be less controversial aspects here compared to [this PR](https://github.com/tensorflow/datasets/pull/32), but once either is resolved I'm happy to modify the other so that all shapenet stuff is sitting together (assuming image -> volume datasets are more `volume`-ous than `image`-ish).

Also happy to add the shapenet ICCV2017 reconstruction track (to partner the point cloud segmentation one) once shape issues with RLE encodings have been resolved.

### CODE REVIEW

**Comment by jackd** [comment]
dataset info [here](https://gist.github.com/jackd/90815cb20fbdabb00d3aafab6773b23a).

**Comment by jackd** [comment]
I have no idea why this presubmit is failing... can't install tensorflow-datasets? All I did was add a lazy import...

**Comment by ataiya** [comment]
Hi @jackd would you like to add this dataset under tensorflow_graphics instead?
I see this has been here for about a year with no updates.

**Comment by jackd** [comment]
@ataiya Yeah, I gave up waiting here/submitting any more PRs and just made a [separate repository](https://github.com/jackd/shape-tfds) with this and some other shape stuff. If it's likely to get through at graphics then I'm happy to clean some of them up, but I wouldn't mind getting a clearer idea of what'll be prioritized at the other end before I make too many PRs like this one.

**Pull request closed without merging**
