### PR TITLE
Update scientific_papers.py

### LINKED ISSUE #1699: [GSoC] Fix scientific_paper dataset
**Short description**

Current dataset generation is broken for `scientific_paper`:

```
tensorflow_datasets/core/dataset_builder.py", line 955, in _download_and_prepare
 0323 08:31:16.738257     self._prepare_split(split_generator, **prepare_split_kwargs)
 0323 08:31:16.738258   File "/py/tensorflow_datasets/core/dataset_builder.py", line 1127, in _prepare_split
 0323 08:31:16.738259     total=split_info.num_examples, leave=False):
 0323 08:31:16.738260   File "/py/tqdm/_tqdm.py", line 979, in __iter__
 0323 08:31:16.738261     for obj in iterable:
 0323 08:31:16.738262   File "/py/tensorflow_datasets/summarization/scientific_papers.py", line 115, in _generate_examples
 0323 08:31:16.738265     for line in f:
 0323 08:31:16.738266   File "tensorflow/python/lib/io/file_io.py", line 211, in __next__
 0323 08:31:16.738267     return self.next()
 0323 08:31:16.738268   File "/tensorflow/python/lib/io/file_io.py", line 205, in next
 0323 08:31:16.738269     retval = self.readline()
 0323 08:31:16.738270   File "/tensorflow/python/lib/io/file_io.py", line 169, in readline
 0323 08:31:16.738271     self._preread_check()
 0323 08:31:16.738272   File "/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
 0323 08:31:16.738273     self.__name, 1024 * 512)
 0323 08:31:16.738275 google3.third_party.tensorflow.python.framework.errors_impl.NotFoundError: no parent directory '/home/tensorflow-datasets/extracts/ZIP.ucid_1lvsqvsFi3W-pE1SqNZI0s8NR_export_download1CQHRyal4p4gv4NAVf5-_pD4o3vOCitRLkq35IcBPAQ/pubmed-release'; /home/tensorflow-datasets/extracts/ZIP.ucid_1lvsqvsFi3W-pE1SqNZI0s8NR_export_download1CQHRyal4p4gv4NAVf5-_pD4o3vOCitRLkq35IcBPAQ/pubmed-release/train.txt; Open on /home/tensorflow-datasets/extracts/ZIP.ucid_1lvsqvsFi3W-pE1SqNZI0s8NR_export_download1CQHRyal4p4gv4NAVf5-_pD4o3vOCitRLkq35IcBPAQ/pubmed-release/train.txt
 0323 08:31:16.738313 [1mDownloading and preparing dataset scientific_papers/pubmed/1.1.1 (download: Unknown size, generated: Unknown size, total: Unknown size) to /home/tensorflow-datasets/datasets/2020-03-23_082941586704.scientific_papers/scientific_papers/pubmed/1.1.1...[0m
 0323 08:31:16.738319 
```

### PR DESCRIPTION
**Pull request by Eshan-Agarwal**
Fixes #1699 
@Conchylicultor  please have a look on updates & sorry for all of trouble due to this minor mistake of me.

Please have a look on this [gist](https://gist.github.com/Eshan-Agarwal/ecd6fc659f3ba17417f0339efb5a46fe) containing `dataset_info.json` for `scientific_papers`.

Also have a look on this [colab](https://colab.research.google.com/drive/1xBl2mi6UThshdxuQxilyVCuRb1B5XxWh) notebook it shows everything works fine now.

### CODE REVIEW

**Comment by Eshan-Agarwal** [comment]
@vijayphoenix  thanks for look this , I mistakenly dothat I will add it again

**Comment by Conchylicultor** [comment]
This was merged internally. I'm not sure why this wasn't marked as merged.

**Comment by Eshan-Agarwal** [comment]
Is there is any problem in tfds-bot ?

**Comment by Conchylicultor** [comment]
Yes, this happen sometimes but your contribution is always recorded: https://github.com/tensorflow/datasets/commit/610a5bf65cdb6bacc5485fe6a40ce56babf41c32

**Pull request closed without merging**
