### PR TITLE
Create DatasetBuilder.md

### LINKED ISSUE #1579: Broken link for `tfds.core.DatasetBuilder`
Link for `tfds.core.DatasetBuilder` is broken in https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md#datasetbuilder

### PR DESCRIPTION
**Pull request by Eshan-Agarwal**
Fixes #1579

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you for your contribution, however, we have recently removed the API github and redirect people instead to: https://www.tensorflow.org/datasets/api_docs/python/tfds

If there are dead link, they should be removed (`tfds.core.DatasetBuilder` is automatically linkified), or updated to redirect to https://www.tensorflow.org/datasets/api_docs/python/tfds

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor should I place https://www.tensorflow.org/datasets/api_docs/python/tfds instead ?

**Comment by vijayphoenix** [comment]
@Eshan-Agarwal there are more dead link on the page. 
You can fix and redirect them to the actual documentation on  https://www.tensorflow.org/datasets/....

**Comment by Eshan-Agarwal** [comment]
@vijayphoenix  okay I will do it

**Pull request closed without merging**
