### PR TITLE
add bair robot pushing 128 x 128 dataset

### PR DESCRIPTION
**Pull request by rushabh-v**
# Add Dataset

* Dataset Name: bair_robot_pushing
* Issue Reference: https://github.com/tensorflow/datasets/issues/2157
  
## Description

<description>
  
## Checklist
* [x] Address all TODO's
* [x] Add alphabetized import to subdirectory's `__init__.py`
* [ ] Run `download_and_prepare` successfully
* [x] Add [checksums file](https://www.tensorflow.org/datasets/add_dataset#2_run_download_and_prepare_locally)
* [x] Properly cite in `BibTeX` format
* [ ] Add passing test(s)
* [x] Add test data
* [x] If using additional dependencies (e.g. `scipy`), use [lazy_imports](https://www.tensorflow.org/datasets/add_dataset#extra_dependencies) (if applicable)
* [x] Add data generation script (if applicable)
* [x] [Lint](https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style) code

### CODE REVIEW

**Comment by martinengelcke** [comment]
Thanks a lot @rushabh-v for putting together this PR. Looks good at first glance. How about changing the class name from BairRobotPushing to BairRobotPushing128 to be more explicit? That would also match the filename where the class if defined. Any issues with running `download_and_prepare`?

**Comment by rushabh-v** [comment]
Sure, I have updated the name to "bair_robot_pushing128".

Just allow me some time for `download_and_prepare`. I tried to do it on google colab but it exceeded the memory limits. So, I am trying it locally now!

**Comment by rushabh-v** [comment]
Sorry for the delay @martinengelcke. 

I tried running `download_and_prepare`. But it gave an error that size 12288 can not be reshaped into 128 x 128. And `12288 = (64 * 64 * 3)`. Am I making any mistake?

**Comment by martinengelcke** [comment]
Hm. It sounds like images from DATA_URL = "http://rail.eecs.berkeley.edu/datasets/bair_robot_pushing_dataset_v0.tar" are 64x64x3 and therefore can't be reshaped?

In #2157 you said it looks like they are 512x640x3. How did you obtain that number?

**Comment by rushabh-v** [comment]
I tried to analyze a tfrecord file from the original dataset, by converting it to frames and obtained that number. I have lost the script I used, so I am trying that again (in case I made any mistake).

**Comment by rushabh-v** [comment]
I checked in the paper and they also used `64 x 64` frames. Search for "resolution" [here](https://www.arxiv-vanity.com/papers/1610.00696/). What I don't understand though is that why the name of the current dataset is `bair_robot_pushing_small`. Should I open a PR to rename it to `bair_robot_pushing`? @martinengelcke

**Comment by rushabh-v** [comment]
As a confirmation, I used the script [here](https://github.com/edenton/svg/blob/master/data/convert_bair.py) to convert the tfrecord files of the dataset into frames. And found that they are indeed `64 x 64`. Trying to convert them to `128 x 128` resulted into `ValueError: not enough image data`.

**Comment by martinengelcke** [comment]
Ah ok, nicely done for figuring this out.

Yeah I agree, the name of the dataset is indeed misleading. I think creating a PR to rename the dataset is a good idea. I closed #2157 and you can also close this PR.

Thanks for your work on this :)

**Comment by rushabh-v** [comment]
Closing the PR! Will open a new one to rename `bair_robot_pushing_small` to `bair_robot_pushing`.

**Pull request closed without merging**
