### PR TITLE
Add lfw

### PR DESCRIPTION
**Pull request by SinghKislay**
Hi @us , Here is the link to [gist](https://gist.github.com/SinghKislay/ca97bbff0df9ed8b6bb661b384702147).

### CODE REVIEW

**Comment by us** [comment]
COOL 👍

**Comment by SinghKislay** [comment]
@us, how do I get it merged?

**Comment by us** [comment]
You couldn't. Just contributors can merged. They merge when they check it. 

Please give old pr link on description. Explain this.

**Comment by SinghKislay** [comment]
Old pull request [link](https://github.com/tensorflow/datasets/pull/260).

**Comment by SinghKislay** [comment]
Hello @cyfra, could you please check if it is good enough to merge. I have tested it and I have downloaded and prepared the dataset([gist](https://gist.github.com/SinghKislay/ca97bbff0df9ed8b6bb661b384702147)) it works fine.

**Comment by us** [comment]
@cyfra @Conchylicultor being_merged.

**Pull request merged**
