### PR TITLE
Add `--namespace` and `--search` flags to `tfds list` CLI

### PR DESCRIPTION
**Pull request by NikhilBartwal**
In continuation to PR #3117 
Issue #3116 
The --namespace` and `--search` flags were added with support for multiple flags in CLI.

### CODE REVIEW

**Comment by NikhilBartwal** [comment]
@jatin-code777 This PR contains the original commits as well as the `--namespace` and `--search` flags in continuation of your code. We can collaborate together and you can simply add further commits for `--type` and `--exclude_community` flags to this PR directly. Thanks!

**Comment by jatin-code777** [comment]
Hi @NikhilBartwal, Although I do appreciate your enthusiasm for collaboration, collaborating in this manner will be... tricky (for one, I cannot push commits to your PR _directly_ and any workaround for this will just create a mess) and I'm sure the reviewers will be troubled.

I might make further changes to my code since what I've published now is a **DRAFT PR** and this will make your changes incompatible. Furthermore, I have already written the code for these flags but I haven't pushed them so as to simplify the task for reviewers so they have to review a small chunk at a time. I also did this because these PRs should be separated.

Note: I clearly write at the end of my PR text
> Will add other flags and options in subsequent PRs

@vijayphoenix Can you please help us out?

**Comment by vijayphoenix** [comment]
I agree with @jatin-code777. Collaboration on any issue should consist of taking up independent tasks and I would suggest please do not include changes of an unmerged PR in another PR. This will only make the task for reviewers harder as we have to look at the same code twice.

Closing this PR for now.

**Comment by NikhilBartwal** [comment]
Hey @vijayphoenix, so should i open a separate PR for the remaining two flags?

**Pull request closed without merging**
