### PR TITLE
updated files and scripts

### PR DESCRIPTION
**Pull request by vinayvr11**
@Conchylicultor 
# Add Dataset and update the random_image_generator.py script.

* Dataset Name: <fake_examples>
  
## Description
Add a dataset with better compressed files and updates random_image_generator.py script.
<description>

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you very much for updating. This is a good start. Seeing the diff helps to see the potentential issues of the script.
I triggered kokoro to test our repository, so we can see wether the dataset tests still pass with those changes.

I observe that some archives takes more space than previously. For instance: `tensorflow_datasets/testing/test_data/fake_examples/cityscapes/disparity_trainextra.zip` (+24.3 KB). This isn't expected as the script should reduce the images size, so I would expect the overall archive size to be reduced.
Also it seems that `.npz` files are changed (e.g. `tensorflow_datasets/testing/test_data/fake_examples/cmaterdb/training-images.npz`). Npz are the numpy format, so we should filter those.

Could you investigate those issues ? Alternatively if you fell tired to work on this issue, you can update the script to only compress images (not achives), so someone else can add the archive compression part.

**Comment by vinayvr11** [comment]
> Thank you very much for updating. This is a good start. Seeing the diff helps to see the potentential issues of the script.
> I triggered kokoro to test our repository, so we can see wether the dataset tests still pass with those changes.
> 
> I observe that some archives takes more space than previously. For instance: `tensorflow_datasets/testing/test_data/fake_examples/cityscapes/disparity_trainextra.zip` (+24.3 KB). This isn't expected as the script should reduce the images size, so I would expect the overall archive size to be reduced.
> Also it seems that `.npz` files are changed (e.g. `tensorflow_datasets/testing/test_data/fake_examples/cmaterdb/training-images.npz`). Npz are the numpy format, so we should filter those.
> 
> Could you investigate those issues ? Alternatively if you fell tired to work on this issue, you can update the script to only compress images (not achives), so someone else can add the archive compression part.

Sure i can do this just need some discussion on it.

**Comment by vinayvr11** [comment]
> > Thank you very much for updating. This is a good start. Seeing the diff helps to see the potentential issues of the script.
> > I triggered kokoro to test our repository, so we can see wether the dataset tests still pass with those changes.
> > I observe that some archives takes more space than previously. For instance: `tensorflow_datasets/testing/test_data/fake_examples/cityscapes/disparity_trainextra.zip` (+24.3 KB). This isn't expected as the script should reduce the images size, so I would expect the overall archive size to be reduced.
> > Also it seems that `.npz` files are changed (e.g. `tensorflow_datasets/testing/test_data/fake_examples/cmaterdb/training-images.npz`). Npz are the numpy format, so we should filter those.
> > Could you investigate those issues ? Alternatively if you fell tired to work on this issue, you can update the script to only compress images (not achives), so someone else can add the archive compression part.
> 
> Sure i can do this just need some discussion on it.
Actually ( tensorflow_datasets/testing/test_data/fake_examples/cityscapes/disparity_trainextra.zip) this file is already very compressed so recompressing this using hashing method will increase it's size. So do we need to find a better way to compress them.

**Comment by vinayvr11** [comment]
> > > Thank you very much for updating. This is a good start. Seeing the diff helps to see the potentential issues of the script.
> > > I triggered kokoro to test our repository, so we can see wether the dataset tests still pass with those changes.
> > > I observe that some archives takes more space than previously. For instance: `tensorflow_datasets/testing/test_data/fake_examples/cityscapes/disparity_trainextra.zip` (+24.3 KB). This isn't expected as the script should reduce the images size, so I would expect the overall archive size to be reduced.
> > > Also it seems that `.npz` files are changed (e.g. `tensorflow_datasets/testing/test_data/fake_examples/cmaterdb/training-images.npz`). Npz are the numpy format, so we should filter those.
> > > Could you investigate those issues ? Alternatively if you fell tired to work on this issue, you can update the script to only compress images (not achives), so someone else can add the archive compression part.
> > 
> > 
> > Sure i can do this just need some discussion on it.
> > Actually ( tensorflow_datasets/testing/test_data/fake_examples/cityscapes/disparity_trainextra.zip) this file is already very compressed so recompressing this using hashing method will increase it's size. So do we need to find a better way to compress them. And how to compress the .npz files do you have any method to do that.

**Comment by Conchylicultor** [comment]
For `.npz`, we should not compress them at all. Simply filtering them.

**Comment by vinayvr11** [comment]
> For `.npz`, we should not compress them at all. Simply filtering them.

Ok and how do we filter them. I get the issue in images these images contains boolean values and performing computation on them convert these values into integer values so the size increases.

**Comment by Conchylicultor** [comment]
> Ok and how do we filter them.

Simply skip the file, like `filename.endswith('.npz')` ?

**Comment by Conchylicultor** [comment]
> I get the issue in images these images contains boolean values and performing computation on them convert these values into integer values so the size increases.

Is there a way to keep the original image type ? Have you searched what other people are doing online ?

**Comment by vinayvr11** [comment]
> > I get the issue in images these images contains boolean values and performing computation on them convert these values into integer values so the size increases.
> 
> Is there a way to keep the original image type ? Have you searched what other people are doing online ?

Actually i have made some changes for this so please check it i am uploading it.

**Comment by vinayvr11** [comment]
> > Ok and how do we filter them.
> 
> Simply skip the file, like `filename.endswith('.npz')` ?

I have uploaded the script with changes.

**Comment by Conchylicultor** [comment]
Thank you for those changes. This is better.

PS: Just a minor point, but it's cleaner to check the type with using `img.dtype == np.bool`, rather than string.

**Comment by vinayvr11** [comment]
> Thank you for those changes. This is better.
> 
> PS: Just a minor point, but it's cleaner to check the type with using `img.dtype == np.bool`, rather than string.

Done

**Comment by vinayvr11** [comment]
> > Thank you for those changes. This is better.
> > PS: Just a minor point, but it's cleaner to check the type with using `img.dtype == np.bool`, rather than string.
> 
> Done

@Conchylicultor : Actually i want to apply for GSOC but can't find the right mail to send the proposal so could you help me in this.

**Comment by Conchylicultor** [comment]
For GSoC, I think you need to register in https://summerofcode.withgoogle.com/

It seems that some images size are still increased size. Could you check ? For example:  test_data/fake_examples/diabetic_retinopathy_detection/train/2_right.jpeg (+142 KB (260%))

Also could you update the files too when you update the script, so I can see whether files size increase.

**Comment by vinayvr11** [comment]
@Conchylicultor :
Same issue some images are precompressed and if we try to compress them with hashing method their size increases.

**Comment by Conchylicultor** [comment]
> Same issue some images are precompressed and if we try to compress them with hashing method their size increases.

What do you mean by "images are precompressed" ? How are they precompressed ? If so can we use the same compression technique they are using to reduce their size too ?

**Comment by vinayvr11** [comment]
Sorry i mean their pixels values are too small.

**Comment by Conchylicultor** [comment]
What do you mean "too small" ? A uniform color image contains less information than an image with texture, so I find it highly surprising that the resulting image took more space.

Could you try to play with the compression options to reduce the quality to the minimum: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg
Those images should be smaller than the original ones

**Comment by vinayvr11** [comment]
ok i am searching some methods to compress these images better.

**Comment by vinayvr11** [comment]
@Conchylicultor : If i save this jpeg format into png then it works but the problem is how do know that when we need to change the format. Or can i change the format.

**Comment by vinayvr11** [comment]
@Conchylicultor : All the  issues are solved now. I just uploaded the script and the updated fake_examples folder. I have checked everything, now no image is larger than its old image.

**Comment by vinayvr11** [comment]
@Conchylicultor : I want to work on some more issues like medium level so could you please help me to get them.

**Comment by Conchylicultor** [comment]
Thank you for the update. I think this is a good start.

However, it doesn't look like all issues are solved.
Skip compression images by checking the file size is suboptimal. Instead you could have played with the compression parameters as suggested above (e.g. `im.save(..., quality=1)`). Some zip files are still much larger after compression (e.g. AudioData.zip is +6MB). The code [isn't properly formatted](https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style).

We can commit this first and update the bug so that someone else can take over and complete this.
You can have a look at our github issue list if you'll like to work on something else.

**Comment by vinayvr11** [comment]
I am using this for code formatting -> pylint --rcfile=pylintrc.txt random_image_generator.py

**Comment by vinayvr11** [comment]
> Thank you for the update. I think this is a good start.
> 
> However, it doesn't look like all issues are solved.
> Skip compression images by checking the file size is suboptimal. Instead you could have played with the compression parameters as suggested above (e.g. `im.save(..., quality=1)`). Some zip files are still much larger after compression (e.g. AudioData.zip is +6MB). The code [isn't properly formatted](https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style).
> 
> We can commit this first and update the bug so that someone else can take over and complete this.
> You can have a look at our github issue list if you'll like to work on something else.

Actually i used these parameters but they won't work. The best compression i achieved is 5MB which is 4MB more than the original one. So that's why i have decided to compress these JPEG into png.

**Comment by vinayvr11** [comment]
Can't we just change the image format because png format compressed image better than jpeg. And we only use this technique for these kind of problems where jpeg not works.

**Comment by Conchylicultor** [comment]
> Can't we just change the image format because png format compressed image better than jpeg. And we only use this technique for these kind of problems where jpeg not works.

The goal of the fake data is to test the dataset generation. If the dataset is using jpeg, then the fake data should also be JPEG.

**Comment by vinayvr11** [comment]
> > Can't we just change the image format because png format compressed image better than jpeg. And we only use this technique for these kind of problems where jpeg not works.
> 
> The goal of the fake data is to test the dataset generation. If the dataset is using jpeg, then the fake data should also be JPEG.

So do you have any other idea because i already tried to tune up those parameters and that works but not as we want.

**Comment by vinayvr11** [comment]
Hello @Conchylicultor : could you please commit my changes and save them as (not achieved) so that i can work on them after sometime. And this is my proposal link for GSOC could you please review this and suggest me if i need to change something [(https://docs.google.com/document/d/1mv32xoGI08JP1wcMiugTyVBzCee7dsyYK_5Uf6SjxEE/edit?usp=sharing)]
Thank you

**Comment by vinayvr11** [comment]
Hello @Conchylicultor : could you please commit my changes and save them as (not achieved) so that i can work on them after sometime. And this is my proposal link for GSOC could you please review this and suggest me if i need to change something 
[Proposal](https://docs.google.com/document/d/1mv32xoGI08JP1wcMiugTyVBzCee7dsyYK_5Uf6SjxEE/edit?usp=sharing)
Thank you

**Comment by Conchylicultor** [comment]
Ok, I can merge this. Could you send a new PR update the previous PR only with the script (without all modified files).
We won't update the files yet while others problems are not fixed.

Also, could you format the code properly using the instructions in: https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style ?

For the proposal, I'm not sure I understand the `tf.image` proposal. Also I think the goal of the GSoC is to focus on one or two bigger more ambitious features.

**Comment by vinayvr11** [comment]
So we can only take one project from these.

**Comment by vinayvr11** [comment]
> Ok, I can merge this. Could you send a new PR update the previous PR only with the script (without all modified files).
> We won't update the files yet while others problems are not fixed.
> 
> Also, could you format the code properly using the instructions in: https://www.tensorflow.org/datasets/add_dataset#5_check_your_code_style ?
> 
> For the proposal, I'm not sure I understand the `tf.image` proposal. TFDS and tf.images are two different things. Also it's not clear which `tf.image` bugs you're talking about. Also I think the goal of the GSoC is to focus on one or two bigger more ambitious features.

Ok but I already used that code style and it shows 10/10 results. I don't know that where the errors was could you please help me with this i want to know the error because i have filtered it soo many times with the custom pylintrc file.

**Comment by Conchylicultor** [comment]
For instance, the docstrings are not correctly formatted, some arguments names don't match:

Instead of:
```
  """ Rewrite the older .tar file into new better compressed one.
        Compression formats supports by this method (.tar.gz, .tgz, .tar.bz2)
            Args:
              _dir: directory path which contain tar compressed file
              path: path from directory to file
  """
```

This should be:
```
"""Rewrite the older .tar file into new better compressed one.

Compression formats supports by this method (.tar.gz, .tgz, .tar.bz2)

Args:
  root_dir: directory path which contain tar compressed file
  tar_filepath: path from directory to file
"""
```

Have you used `pylint --rcfile=/path/to/pylintrc my_file.py` ?

**Comment by vinayvr11** [comment]
> For instance, the docstrings are not correctly formatted, some arguments names don't match:
> 
> Instead of:
> 
> ```
>   """ Rewrite the older .tar file into new better compressed one.
>         Compression formats supports by this method (.tar.gz, .tgz, .tar.bz2)
>             Args:
>               _dir: directory path which contain tar compressed file
>               path: path from directory to file
>   """
> ```
> 
> This should be:
> 
> ```
> """Rewrite the older .tar file into new better compressed one.
> 
> Compression formats supports by this method (.tar.gz, .tgz, .tar.bz2)
> 
> Args:
>   root_dir: directory path which contain tar compressed file
>   tar_filepath: path from directory to file
> """
> ```
> 
> Have you used `pylint --rcfile=/path/to/pylintrc my_file.py` ?

Ok thank you and yes i have used the same command but this won't show me any docstring error.

**Comment by vinayvr11** [comment]
@Conchylicultor : I have sended you the new PR please have a look.

**Comment by Conchylicultor** [comment]
Closing in favor of https://github.com/tensorflow/datasets/pull/1661

**Pull request closed without merging**
