### PR TITLE
Fix line endings for URL checksum files on Windows

### LINKED ISSUE #769: download mnist using python 3.7.4
when i try to download the mnist using the below commands:

```
import tensorflow_datasets as tfds
import tensorflow as tf

tf.enable_eager_execution()
mnist_builder = tfds.builder("mnist")
mnist_builder.download_and_prepare()


it shows the following error message:

Dl Completed...: 0 url [00:00, ? url/s]
Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\api_utils.py", line 52, in disallow_positional_args_dec
    return fn(*args, **kwargs)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\dataset_builder.py", line 287, in download_and_prepare
    download_config=download_config)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\dataset_builder.py", line 906, in _download_and_prepare
    max_examples_per_split=download_config.max_examples_per_split,
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\dataset_builder.py", line 762, in _download_and_prepare
    for split_generator in self._split_generators(dl_manager):
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\image\mnist.py", line 132, in _split_generators
    {k: urllib.parse.urljoin(self.URL, v) for k, v in filenames.items()})
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\download_manager.py", line 359, in download_and_extract
    return _map_promise(self._download_extract, url_or_urls)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\download_manager.py", line 394, in _map_promise
    all_promises = utils.map_nested(map_fn, all_inputs)  # Apply the function
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\utils\py_utils.py", line 129, in map_nested
    for k, v in data_struct.items()
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\utils\py_utils.py", line 129, in <dictcomp>
    for k, v in data_struct.items()
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\utils\py_utils.py", line 143, in map_nested
    return function(data_struct)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\util.py", line 97, in lock_decorated
    return fn(*args, **kwargs)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\download_manager.py", line 277, in _download_extract
    return self._download(resource).then(callback)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\util.py", line 97, in lock_decorated
    return fn(*args, **kwargs)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\download_manager.py", line 228, in _download
    download_path = self._get_final_dl_path(url, expected_sha256)
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\download_manager.py", line 188, in _get_final_dl_path
    resource_lib.get_dl_fname(url, sha256))
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\resource.py", line 187, in get_dl_fname
    checksum = base64.urlsafe_b64encode(_decode_hex(checksum))
  File "D:\data\TensorFlow\Dataset\tensorflow_datasets\core\download\resource.py", line 44, in _decode_hex
    return _hex_codec(hexstr)[0]
  File "C:\Users\edwinzeng\AppData\Local\Programs\Python\Python37\lib\encodings\hex_codec.py", line 19, in hex_decode
    return (binascii.a2b_hex(input), len(input))
binascii.Error: Odd-length string
```

**Environment information**
* Operating System: Win10
* Python version: 3.7.4
* `tensorflow-datasets`/`tfds-nightly` version: 1.0.2
* `tensorflow`/`tensorflow-gpu`/`tf-nightly`/`tf-nightly-gpu` version: 1.14.0

Thank you.

### PR DESCRIPTION
**Pull request by 20zinnm**
Resolves #769. Tested on my Windows 10 machine.

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Great thank you very much! This seems a better fix. Merging it now.

**Comment by 20zinnm** [comment]
@Conchylicultor no clue what's up with kokoro, I didn't see anything in the build error related to the checksums.

**Comment by Conchylicultor** [comment]
No worries, this is a bug from a recent PR, not related to this change.

**Comment by Conchylicultor** [comment]
Should be fixed with https://github.com/tensorflow/datasets/commit/76325da2ec1d7a388f9965daf027299a5d138631 (even if it may need 24 hours for the new tfds-nightly to be released), so closing this.

Thanks again for your help

**Pull request closed without merging**
