### PR TITLE
Added test and fake data for librispeech

### LINKED ISSUE #155: Add test and fake data for librispeech
Librispeech is missing unittest and fake data.

Please follow:
https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md#testing-mydataset

### PR DESCRIPTION
**Pull request by ChanchalKumarMaji**
Fixes #155 ,
test and fake data has been added for librispeech.

@rsepassi @Conchylicultor @cyfra please check.

### CODE REVIEW

**Comment by ChanchalKumarMaji** [comment]
> Thank you! Could you please clear out the README files? Fine to have them, but they don't need to have real content in them. Only put content in the files that actually need it for data generation.

All the README files are needed to be cleared, or some, because I manually filled them. I dont know but clearing them could create some issues ?

**Comment by ChanchalKumarMaji** [comment]
But I cannot edit the files ? Why ?

**Comment by rsepassi** [comment]
So when you submit a pull request, you can make updates to it by making additional commits on your local git repo and pushing them to your fork. The PR will automatically update based on those additional commits.

**Comment by rsepassi** [comment]
Yes, please do.

**Pull request closed without merging**
