### PR TITLE
Update data URLs

### PR DESCRIPTION
**Pull request by lmoroney**
Change data source URLs from lmoroney's bucket to tensorflow.org

  
## Description

Updating data URLs to use tensorflow.org instead of mine
  
## Checklist
* [ ] Address all TODO's
* [ ] Add alphabetized import to subdirectory's `__init__.py`
* [ ] Run `download_and_prepare` successfully
* [ ] Add checksums file
* [ ] Properly cite in `BibTeX` format
* [ ] Add passing test(s)
* [ ] Add test data
* [ ] Add data generation script (if applicable)
* [ ] Lint code

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Any updates ?

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  Can I make changes ? for this and similar #1920

**Comment by Conchylicultor** [comment]
> @Conchylicultor Can I make changes ? for this and similar #1920

@Eshan-Agarwal, thank you. Yes, don't hesitate to take over the PR.

**Comment by Eshan-Agarwal** [comment]
This and similar #1920 can be close as #1974 merged

**Comment by Conchylicultor** [comment]
Yes, thank you @Eshan-Agarwal for your quick implementation.

**Pull request closed without merging**
