### PR TITLE
Added UCI Adult Dataset with proper ClassLabels

### PR DESCRIPTION
**Pull request by VaranRohila**
# Add Dataset

* Dataset Name: UCI Adult Dataset
* dataset_info.json: [link](https://gist.github.com/VaranRohila/aaa36aa3cdcbb48db8dab5a43e96231e#file-dataset_info-json)

## Description

The dataset contains various information about adults.
The purpose of the dataset is to predict whether the 
the person earns more than $50K/year or not.
  
## Checklist
* [x] Address all TODO's
* [x] Add alphabetized import to subdirectory's `__init__.py`
* [x] Run `download_and_prepare` successfully
* [x] Add checksums file
* [x] Properly cite in `BibTeX` format
* [x] Add passing test(s)
* [x] Add test data
* [x] Add data generation script (if applicable)
* [x] Lint code

## Additional Notes

* The columns have been converted to tfds.features.ClassLabel wherever applicable.
* Both test and train datasets have been incorporated.
* Tensorflow ML model is also tested with input pipeline from tfds.

### CODE REVIEW

**Comment by VaranRohila** [comment]
@googlebot I signed it!

**Comment by VaranRohila** [comment]
Issue [link](https://github.com/tensorflow/datasets/issues/1335)

**Comment by ChanchalKumarMaji** [comment]
Please create separate branches for each work. I think you have mixed some other PRs.

**Comment by VaranRohila** [comment]
I'll just fix it

**Comment by VaranRohila** [comment]
I created another branch and PR [here](https://github.com/tensorflow/datasets/pull/1609). Sorry about that.

**Pull request closed without merging**
