### PR TITLE
Update Broken links 

### PR DESCRIPTION
**Pull request by Eshan-Agarwal**
Update Broken links on : https://github.com/tensorflow/datasets/blob/master/docs/add_dataset.md#datasetbuilder

### CODE REVIEW

**Comment by Conchylicultor** [comment]
Thank you. Note that the links are automatically added when the website documentation gets generated.

Basically instead of:
```
`_info`: builds the [`DatasetInfo`](https://www.tensorflow.org/datasets/api_docs/python/tfds/core/DatasetInfo) object
```
Just have
```
`_info`: builds the `tfds.core.DatasetInfo` object
```

This would avoid future dead links if the website get's updated or paths changes.

**Comment by Eshan-Agarwal** [comment]
So can I remove all links ?

**Comment by Conchylicultor** [comment]
Yes, exactly!

**Comment by Eshan-Agarwal** [comment]
Ok Working on it

**Comment by Eshan-Agarwal** [comment]
@Conchylicultor  have a look if there is anything else to do ?

**Comment by Conchylicultor** [comment]
Looks good! Merging this soon!

**Pull request merged**
